MaaAahwanam.Web/Controllers/ChangePasswordController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MaaAahwanam.Models;
using MaaAahwanam.Utility;
using System.Configuration;
using System.Web.Security;
using MaaAahwanam.Service;
namespace MaaAahwanam.Web.Controllers
{
    public class ChangePasswordController : Controller
    {
        //
        // GET: /ChangePassword/
        public ActionResult Index()
        {
            if (ValidUserUtility.ValidUser() != 0 && (ValidUserUtility.UserType() == "User" || ValidUserUtility.UserType() == "Vendor"))
            {
                ViewBag.Type = ValidUserUtility.UserType();
            }   
            return View();
        }
        [HttpPost]
        public ActionResult Index(UserLogin userLogin)
        {
            UserLoginDetailsService userLoginDetailsService = new UserLoginDetailsService();
            userLoginDetailsService.changepassword(userLogin, ValidUserUtility.ValidUser());
            return View();
        }
	}
}

MaaAahwanam.Web/Views/ChangePassword/Index.cshtml
@model MaaAahwanam.Models.UserLogin
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/SharedWeb/DashBoardMaster.cshtml";
}

@section Navigation
{
    <div class="breads">
        <div class="breads_inner">
            <div class="pageWidth">
                <div class="title">
                    <h3>Change Password</h3>
                </div>
                <div class="breadcrumbs">
                    <ul>
                        @if (ViewBag.Type == "User")
                        {
                            <li><a href="~/index/Index">Home</a></li>
                        }
                        <li><i class="breads_arrow"></i></li>
                        <li><a href="../Dashboard">Dashboard</a></li>
                        <li><i class="breads_arrow"></i></li>
                        <li>Change Password</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
}

<div class="change-pwd">
    @using (Html.BeginForm("Index", "ChangePassword", FormMethod.Post, new { @class = "form", @id = "change_password", @autocomplete = "off" }))
    {
        <ul>
            <li>
                <label>New Password<span>*</span></label>
                @*<input type="text" id="npwd" name="npwd" placeholder="New Password">*@
                @Html.TextBoxFor(model => model.Password, new {@class = "form-control", @id = "npwd", @name = "npwd", placeholder = "New Password", required = "required" })
            </li>
        </ul>
        <ul>
            <li>
                <label>Confirm Password<span>*</span></label>
                @*<input type="text" id="cpwd" name="cpwd" placeholder="Confirm Password">*@
                @Html.TextBoxFor(Model => Model.Password, new {@class = "form-control", @id = "cpwd", @name = "cpwd", placeholder = "Confirm Password", required = "required" })
            </li>
        </ul>
        <div class="btn-left">
            @*<button type="submit" id="btnSubmit" class="btn btn btn-orange m-l-0" onclick="check();"><i class="ti-save"></i>Save</button>*@
            <button class="btn text-muted text-center btn-success" name="Command" value="Register" type="submit" onclick="check();">Register</button>
            <button type="submit" class="btn btn btn-red" ><i class=" ti-close"></i>Cancel</button>
            <div class="clear"></div>
        </div>
        @*</form>*@
    }
        <div class="clear"></div>
</div>
<script>
    function check() {
        alert('aa');
        //if (document.getElementById("npwd").value === document.getElementById("cpwd").value) {
        //    cpwd.setCustomValidity("");
        //}
        //else {
        //    cpwd.setCustomValidity("Passwords Don't Match");
        //}
    }
</script>